// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BenefitMarketSegment", b =>
                {
                    b.Property<int>("BenefitsId")
                        .HasColumnType("int");

                    b.Property<int>("MarketSegmentsId")
                        .HasColumnType("int");

                    b.HasKey("BenefitsId", "MarketSegmentsId");

                    b.HasIndex("MarketSegmentsId");

                    b.ToTable("BenefitMarketSegment");
                });

            modelBuilder.Entity("BenefitProduct", b =>
                {
                    b.Property<int>("BenefitsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("BenefitsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductsBenefits", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AbrasionResistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AbrasionResistances");
                });

            modelBuilder.Entity("Domain.Models.AbrasionResistanceDescription", b =>
                {
                    b.Property<int>("AbrasionResistanceId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbrasionResistanceId", "Language");

                    b.ToTable("AbrasionResistanceDescriptions");
                });

            modelBuilder.Entity("Domain.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("Domain.Models.BenefitCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BenefitCategories");
                });

            modelBuilder.Entity("Domain.Models.BenefitCategoryDescription", b =>
                {
                    b.Property<int>("CategoryOfBenefitId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int?>("BenefitCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryOfBenefitId", "Language");

                    b.HasIndex("BenefitCategoryId");

                    b.ToTable("BenefitCategoryDescriptions");
                });

            modelBuilder.Entity("Domain.Models.BenefitDescription", b =>
                {
                    b.Property<int>("BenefitId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenefitId", "Language");

                    b.ToTable("BenefitDescriptions");
                });

            modelBuilder.Entity("Domain.Models.MarketSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketSegments");
                });

            modelBuilder.Entity("Domain.Models.MarketSegmentDescription", b =>
                {
                    b.Property<int>("MarketSegmentId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarketSegmentId", "Language");

                    b.ToTable("MarketSegmentDescriptions");
                });

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AbrasionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AbrasionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Models.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarrantyLengthId")
                        .HasColumnType("int");

                    b.Property<int?>("WarrantyNotabeneId")
                        .HasColumnType("int");

                    b.Property<int>("WarrantyTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarrantyLengthId");

                    b.HasIndex("WarrantyNotabeneId");

                    b.HasIndex("WarrantyTitleId");

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("Domain.Models.WarrantyLength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WarrantyLengths");
                });

            modelBuilder.Entity("Domain.Models.WarrantyLengthDescription", b =>
                {
                    b.Property<int>("WarrantyLengthId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyLengthId", "Language");

                    b.ToTable("WarrantyLengthDescriptions");
                });

            modelBuilder.Entity("Domain.Models.WarrantyNotabene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WarrantyNotabenes");
                });

            modelBuilder.Entity("Domain.Models.WarrantyNotabeneDescription", b =>
                {
                    b.Property<int>("WarrantyNotabeneId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyNotabeneId", "Language");

                    b.ToTable("WarrantyNotabeneDescriptions");
                });

            modelBuilder.Entity("Domain.Models.WarrantyTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WarrantyTitles");
                });

            modelBuilder.Entity("Domain.Models.WarrantyTitleDescription", b =>
                {
                    b.Property<int>("WarrantyTitleId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyTitleId", "Language");

                    b.ToTable("WarrantyTitleDescriptions");
                });

            modelBuilder.Entity("ProductWarranty", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("WarrantiesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "WarrantiesId");

                    b.HasIndex("WarrantiesId");

                    b.ToTable("ProductWarranty");
                });

            modelBuilder.Entity("BenefitMarketSegment", b =>
                {
                    b.HasOne("Domain.Models.Benefit", null)
                        .WithMany()
                        .HasForeignKey("BenefitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.MarketSegment", null)
                        .WithMany()
                        .HasForeignKey("MarketSegmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenefitProduct", b =>
                {
                    b.HasOne("Domain.Models.Benefit", null)
                        .WithMany()
                        .HasForeignKey("BenefitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AbrasionResistanceDescription", b =>
                {
                    b.HasOne("Domain.Models.AbrasionResistance", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("AbrasionResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Benefit", b =>
                {
                    b.HasOne("Domain.Models.BenefitCategory", "Category")
                        .WithMany("Benefits")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.BenefitCategoryDescription", b =>
                {
                    b.HasOne("Domain.Models.BenefitCategory", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("BenefitCategoryId");
                });

            modelBuilder.Entity("Domain.Models.BenefitDescription", b =>
                {
                    b.HasOne("Domain.Models.Benefit", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.MarketSegmentDescription", b =>
                {
                    b.HasOne("Domain.Models.MarketSegment", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("MarketSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.HasOne("Domain.Models.AbrasionResistance", "Abrasion")
                        .WithMany("Products")
                        .HasForeignKey("AbrasionId");

                    b.Navigation("Abrasion");
                });

            modelBuilder.Entity("Domain.Models.Warranty", b =>
                {
                    b.HasOne("Domain.Models.WarrantyLength", "WarrantyLength")
                        .WithMany()
                        .HasForeignKey("WarrantyLengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.WarrantyNotabene", "WarrantyNotabene")
                        .WithMany()
                        .HasForeignKey("WarrantyNotabeneId");

                    b.HasOne("Domain.Models.WarrantyTitle", "WarrantyTitle")
                        .WithMany()
                        .HasForeignKey("WarrantyTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarrantyLength");

                    b.Navigation("WarrantyNotabene");

                    b.Navigation("WarrantyTitle");
                });

            modelBuilder.Entity("Domain.Models.WarrantyLengthDescription", b =>
                {
                    b.HasOne("Domain.Models.WarrantyLength", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("WarrantyLengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.WarrantyNotabeneDescription", b =>
                {
                    b.HasOne("Domain.Models.WarrantyNotabene", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("WarrantyNotabeneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.WarrantyTitleDescription", b =>
                {
                    b.HasOne("Domain.Models.WarrantyTitle", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("WarrantyTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductWarranty", b =>
                {
                    b.HasOne("Domain.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Warranty", null)
                        .WithMany()
                        .HasForeignKey("WarrantiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AbrasionResistance", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Models.Benefit", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Domain.Models.BenefitCategory", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Domain.Models.MarketSegment", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Domain.Models.WarrantyLength", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Domain.Models.WarrantyNotabene", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("Domain.Models.WarrantyTitle", b =>
                {
                    b.Navigation("Descriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
